name: pyAnalytics
dependencies:
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - imageio
  - scikit-learn
  - scipy
  - pip
  - pip:
    - little_helpers
    - pyPreprocessing
    - pyDataFitting
    - spc
